name: Own Units Tests

on: [push, pull_request]

jobs:
  launch_tester_linux:
    runs-on: ubuntu-latest
    name: Own Tester Linux
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install Progs for Tester
        run: |
          sudo apt update
          sudo apt install -y bash clang valgrind
      - name: Environnement Informations
        run: |
          echo OS version
          lsb_release -a
          echo
          echo Linux kernel version
          uname -r
          echo
          echo Clang version
          clang++ --version
          echo
          echo Valgrind version
          valgrind --version
        shell: bash
      - name: Launch Script
        run: ./vector_test.sh
        shell: bash
      - name: Launch Script with Capacity check
        run: ./vector_test.sh capacity
        shell: bash
        continue-on-error: true
  launch_tester_macos:
    runs-on: macos-latest
    name: Own Tester MacOS
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        continue-on-error: true
      - name: Environnement Informations
        run: |
          echo OS version
          system_profiler SPSoftwareDataType
          echo
          echo Clang version
          clang++ --version
      - name: Launch Script
        run: ./vector_test.sh
        shell: bash
      - name: Launch Script with Capacity check
        run: ./vector_test.sh capacity
        shell: bash
        continue-on-error: true
